name: Pull Request

on: [pull_request]

jobs: 
    install: 
        name: Installing Packages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cache node_modules
              uses: actions/checkout@v2
              with:
                path: node_modules
                key: ${{runner.os }}-${{hashFiles('**/package-lock.json')}}

            - name: Install dependecies
              run: npm install


